#!/bin/sh

#########################################################
# Script:       picotts                                 #
# Version:      0.2                                     #
# Author:       Adeel Ahmad (codegenki)                 #
# Date Created: Feb 9, 2021                             #
# Date Mod.:    Dec 8, 2025                             #
# Usage:        picotts                                 #
# Description:  Script to play TTS for some text        #
#########################################################

APP_NAME=$(basename $0)

# check availability of TTS engine
_talk=`command -v pico2wave`
if [ -z "$_talk" ]; then
  echo "Missing dependency: install SVOX Pico engine!" >&2
  exit 1
fi

# detect & decide audio player
_player1=`command -v ffplay`
_player2=`command -v aplay`
if [ -z "$_player1" -a -z "$_player2" ]; then
  echo "Missing dependency: install either of [alsa-utils, ffmpeg]" >&2
  exit 1
fi
[ -n "$_player1" ] && _play="$_player1 -hide_banner -nodisp -autoexit"
[ -z "$_play" ] && _play="$_player2 -q"

# help msg
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Usage: $APP_NAME <lang> <msg>"
  echo "Langs: en-US, en-GB, es-ES, de-DE, fr-FR, it-IT"
  exit 0
fi

# error: not enough arguments
if [ $# -lt 2 ]; then
  echo "$APP_NAME: not enough arguments" >&2
  exit 1
fi

# check for available languages
case "$1" in
  en-US|en-GB|es-ES|de-DE|fr-FR|it-IT)
    ;;
  *)
    echo "$APP_NAME: unsupported language: $1" >&2
    exit 1
    ;;
esac

# create temp file
tmpfile=$(mktemp -tp /tmp picoSndXXXXXX)
tmpfilewav="$tmpfile.wav"
mv "$tmpfile" "$tmpfilewav"

# extract language argument
lang_pico=$1
shift

# play message
$_talk -l $lang_pico -w "$tmpfilewav" "$*"
$_play "$tmpfilewav" 2>/dev/null

# delete temp file
rm "$tmpfilewav"

