#!/bin/sh

#########################################################
# Script:       picotts-sel                             #
# Version:      0.2                                     #
# Author:       Adeel Ahmad (codegenki)                 #
# Date Created: Feb 9, 2021                             #
# Date Mod.:    Dec 8, 2025                             #
# Usage:        picotts-sel                             #
# Description:  Script to play TTS for selected text    #
#########################################################

APP_NAME=$(basename $0)

# detect & decide selector application
_selector=
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  [ -n $(command -v wl-paste) ] &&
    _selector="$(command -v wl-paste) --primary --no-newline" ||
    {
      echo "wl-paste required in wayland session! Install wl-clipboard."
      return 1
    }
elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
  [ -n $(command -v xsel) ] &&
    _selector="$(command -v xsel) -o" ||
    {
      echo "xsel required in x11 session! Install xsel."
      return 1
    }
fi

# help message
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Usage: $APP_NAME"
  echo "Language will be automatically detected from system locale"
  echo "Supported languages: English, Spanish, German, French and Italian"
  exit 0
fi

# no arg required
if [ "$#" -eq 0 ]; then
  # get language configured in locale environment variable
  if [ "$LC_ALL" != "" ]; then
    lang=$LC_ALL
  elif [ "$LC_MESSAGES" != "" ]; then
    lang=$LC_MESSAGES
  elif [ "$LANG" != "" ]; then
    lang=$LANG
  else
    lang="C"
  fi

  # check if language is supported by picoTTS
  case "$lang" in
  en_US*)
    lang_pico="en-US"
    ;;
  en*)
    lang_pico="en-GB"
    ;;
  es*)
    lang_pico="es-ES"
    ;;
  de*)
    lang_pico="de-DE"
    ;;
  fr*)
    lang_pico="fr-FR"
    ;;
  it*)
    lang_pico="it-IT"
    ;;
  *)
    echo "$APP_NAME: unsupported language: $lang" >&2
    exit 1
    ;;
  esac

  # get selection from X server/wayland
  sayit=$(eval $_selector)
  if [ -n "$sayit" ]; then
    # play selection text
    $HOME/bin/picotts $lang_pico $sayit
  else
    # error: no text selected
    echo "$APP_NAME: no text selected, select some text before invoking." >&2
    exit 1
  fi
fi
